---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install some packages
    package:
      name:
        - htop
        - tmux
        - nmon
        - pydf
        - fzf
        - cmus
        - mc